### ISSUE TITLE
Wrong <request> information item in response document

### ISSUE THREAD

**Issue by dmj** [wendig-ou/hab-oai-pmh#1]
The &lt;request> information item in most response documents is wrong.

- it should list all request parameters as attributes
- it should contain the base URL of the protocol request

In many only contains the verb, the wrong verb and the request URL.

https://github.com/wendig-ou/hab-oai-pmh/blob/b8b66955653f5d2687a5b43095a25cea9d627013/app/oai.xqm#L160

**Comment by moritzschepp** [comment]
Indeed!

I just fixed this.
